# Generated by Django 5.1 on 2024-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='image.png', upload_to=''),
            preserve_default=False,
        ),
    ]
