# Generated by Django 5.1 on 2024-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.CharField(default='fa-pencil-alt', max_length=255),
            preserve_default=False,
        ),
    ]
